### ISSUE TITLE
Make it so that Trevis shows only the build status for the master branch

### ISSUE THREAD

**Issue by patrnk** [Stark-Mountain/meetup-facebook-bot#35]
We now have `build: failing` because one of the branches has a failing build, not the `master`. This is misleading.

**Comment by patrnk** [comment]
Closed by 1ed57d19261736bc9bffce0c039db1e3e44baaed

**Comment by patrnk** [comment]
Not actually closed.

**Comment by voron434** [comment]
I've already done it, just gonna close 1 more travis issue and send pr with both of them
